export const API_URL = 'http://localhost:8080'

/* action types */
export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_LOGGED = 'USER_LOGGED';
export const USER_LOGIN_ERROR = 'USER_LOGIN_ERROR';
export const USER_REGISTER = 'USER_REGISTER';
export const USER_REGISTERED = 'USER_REGISTERED';
export const USER_REGISTER_ERROR = 'USER_REGISTER_ERROR';
export const USER_SET_PERSONAL_INFO_REQUEST = 'USER_SET_PERSONAL_INFO_REQUEST';
export const USER_SET_PERSONAL_INFO = 'USER_SET_PERSONAL_INFO';
export const USER_SET_PERSONAL_INFO_ERROR = 'USER_SET_PERSONAL_INFO_ERROR';
export const USER_UPDATE = 'USER_UPDATE';
export const USER_UPDATED = 'USER_UPDATED';
export const USER_UPDATE_ERROR = 'USER_UPDATE_ERROR';
export const USER_INFO_CHANGE = 'USER_INFO_CHANGE';
export const USER_CHANGE_PASSWORD = 'USER_CHANGE_PASSWORD';
export const USER_CHANGE_PASWORD_SUCCESS = 'USER_CHANGE_PASWORD_SUCCESS';
export const USER_CHANGE_PASWORD_ERROR = 'USER_CHANGE_PASWORD_ERROR';

export const ROUTE_CHANGED = 'ROUTE_CHANGED';

export const PRODUCTS_GET_ALL = 'PRODUCTS_GET_ALL';

export const ERROR_CLASS = 'has-error';