export const API_URL = 'http://localhost:8080'

/* action types */
/* user action types */
export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_ERROR = 'USER_LOGIN_ERROR';

export const USER_LOGOUT = 'USER_LOGOUT';

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_ERROR = 'USER_REGISTER_ERROR';

export const USER_SET_PERSONAL_INFO_REQUEST = 'USER_SET_PERSONAL_INFO_REQUEST';
export const USER_SET_PERSONAL_INFO_SUCCESS = 'USER_SET_PERSONAL_INFO_SUCCESS';
export const USER_SET_PERSONAL_INFO_ERROR = 'USER_SET_PERSONAL_INFO_ERROR';

export const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST';
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';
export const USER_UPDATE_ERROR = 'USER_UPDATE_ERROR';

export const USER_CHANGE_PASSWORD_REQUEST = 'USER_CHANGE_PASSWORD_REQUEST';
export const USER_CHANGE_PASWORD_SUCCESS = 'USER_CHANGE_PASWORD_SUCCESS';
export const USER_CHANGE_PASWORD_ERROR = 'USER_CHANGE_PASWORD_ERROR';

/* admin action types */
export const ADMIN_GET_ALL_USERS_REQUEST = 'ADMIN_GET_ALL_USERS_REQUEST';

export const ADMIN_GET_USER_REQUEST = 'ADMIN_GET_USER_REQUEST';
export const ADMIN_GET_USER_SUCCESS = 'ADMIN_GET_USER_SUCCESS';
export const ADMIN_GET_USER_ERROR = 'ADMIN_GET_USER_ERROR';

export const ADMIN_UPDATE_REQUEST = 'ADMIN_UPDATE_REQUEST';
export const ADMIN_UPDATE_SUCCESS = 'ADMIN_UPDATE_SUCCESS';
export const ADMIN_UPDATE_ERROR = 'ADMIN_UPDATE_ERROR';

export const ADMIN_SEARCH_USERS_REQUEST = 'ADMIN_SEARCH_USERS_REQUEST';
export const ADMIN_SEARCH_USERS_SUCESS = 'ADMIN_SEARCH_USERS_SUCESS';
export const ADMIN_SEARCH_USERS_ERROR = 'ADMIN_SEARCH_USERS_ERROR';

export const ADMIN_CHANGE_SEARCH_FIELD = 'ADMIN_CHANGE_SEARCH_FIELD';

export const ADMIN_DELETE_USER_REQUEST = 'ADMIN_DELETE_USER_REQUEST';
export const ADMIN_DELETE_USER_SUCCESS = 'ADMIN_DELETE_USER_SUCCESS';
export const ADMIN_DELETE_USER_ERROR = 'ADMIN_DELETE_USER_ERROR';

export const ADMIN_CHANGE_USER_PASSWORD_REQUEST = 'ADMIN_CHANGE_USER_PASSWORD_REQUEST';
export const ADMIN_CHANGE_USER_PASSWORD_SUCCESS = 'ADMIN_CHANGE_USER_PASSWORD_SUCCESS';
export const ADMIN_CHANGE_USER_PASSWORD_ERROR = 'ADMIN_CHANGE_USER_PASSWORD_ERROR';

///ss
export const ROUTE_CHANGED = 'ROUTE_CHANGED';

export const PRODUCTS_GET_ALL = 'PRODUCTS_GET_ALL';

export const ERROR_CLASS = 'has-error';